services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    # runs inside entrypoint.sh when the container starts
    command: /start
    image: estate_prod_api
    container_name: estate_prod_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
    networks:
      - estate_prod_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: estate_prod_postgres
    container_name: estate_prod_postgres
    ports:
      - "5432:5432"
    volumes:
      # postgres is running in a container, and if stopped, the data will be lost
      # so we need to persist the data in a volume to preserve it
      - estate_prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - estate_prod_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: estate_prod_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      # preserves the mailpit data in a volume so that emails are not lost
      - estate_prod_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - estate_prod_nw

  client:
    build:
      context: ./client
      dockerfile: ./docker/local/Dockerfile
    container_name: estate_client
    image: estate_client
    # ports:
    #   - "3000:3000"
    expose:
      # expose the port to services in the same network
      - "3000"
    volumes:
      - ./client:/app
      # ensures that the node_modules in the container are not overwritten by the host
      - /app/node_modules
    networks:
      - estate_prod_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: estate_redis
    volumes:
      - estate_redis_prod_data:/data
    networks:
      - estate_prod_nw

  celeryworker:
    # copy the config from the api service
    <<: *api
    image: estate_prod_celeryworker
    container_name: estate_prod_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *api
    image: estate_prod_celerybeat
    container_name: estate_prod_celerybeat
    command: /start-celerybeat

  flower:
    # copy the config from the api service
    <<: *api
    image: estate_prod_flower
    container_name: estate_prod_flower
    ports:
      - "5555:5555"
    command: /start-flower

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: estate_nginx
    ports:
      - "8080:80"
    volumes:
      # any changes to the static files will be reflected in the nginx and api container
      - ./staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - estate_prod_nw

networks:
  # created using docker network create estate_prod_nw
  estate_prod_nw:
    external: true

volumes:
  estate_prod_postgres_data: {}
  estate_prod_mailpit_data: {}
  logs_store: {}
  estate_redis_prod_data: {}
